FROM centos:7
MAINTAINER Tuhin Sharma <tusharma@redhat.com>

RUN yum install -y epel-release && \
    yum install -y python-pip python-devel gcc && \
    yum install -y zip && \
    yum clean all


# --------------------------------------------------------------------------------------------------
# install python packages
# --------------------------------------------------------------------------------------------------
COPY ./analytics_platform/gnosis/requirements.txt /
RUN pip install -r /requirements.txt && rm /requirements.txt
RUN pip install pomegranate==0.7.3

# --------------------------------------------------------------------------------------------------
# copy src code and scripts into root dir /
# the rest_api.py code assumes this dir structure
# --------------------------------------------------------------------------------------------------
COPY ./analytics_platform/gnosis/deployment/rest_api.py /rest_api.py
COPY ./analytics_platform/gnosis/scripts/bootstrap_action.sh /
COPY ./analytics_platform /analytics_platform
COPY ./util /util
COPY ./analytics_platform/gnosis/src/config.py.template /analytics_platform/gnosis/src/config.py


# --------------------------------------------------------------------------------------------------
# add entrypoint for the container
# --------------------------------------------------------------------------------------------------
ADD ./analytics_platform/gnosis/scripts/entrypoint.sh /bin/entrypoint.sh

ENTRYPOINT ["/bin/entrypoint.sh"]
