apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: janus
  name: janus
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: janus
status:
  loadBalancer: {}
